### ISSUE TITLE
9.0.0

### ISSUE THREAD

**Issue by Witherking25** [nadrino/SimpleModManager#1]
Can you update this to work with the latest libnx?
hid input wont work until you do so, rendering the application useless until then

**Comment by simplyimpossible** [comment]
Experiencing the same problem.
Would be greatly appreciated to fix this because I love the look of this app.

**Comment by nadrino** [comment]
Oh, this is strange I did not had the problem on 9.0.0 but I will update to the latest libnx.

**Comment by nadrino** [comment]
Ok guys, I've published a new release. Tell me if you still experience troubles

**Comment by simplyimpossible** [comment]
Nope, it works perfectly fine! Thanks for responding so fast!

**Comment by Witherking25** [comment]
It works now. Thanks!
