### ISSUE TITLE
Mod titles are cut off when too long

### ISSUE THREAD

**Issue by pixeltester** [nadrino/SimpleModManager#11]
If the title of the mod is too long for the horizontal screen space it gets cut off, is it possible to make the text scroll in this case?

Maybe your GUI will take care of the issue?

**Comment by nadrino** [comment]
Exactly, the GUI is automatically taking care of this!
It's a bit more complicated to implement it in the console mode.

**Comment by pixeltester** [comment]
It looks like it's actually worse with the new GUI because we can no longer see the status as seen in your screenshot:

https://raw.githubusercontent.com/nadrino/SimpleModManager/master/screenshots/2.jpg

Also it's affecting game titles especially if you include the titleid in the title.

**Comment by pixeltester** [comment]
Just wanted to suggest to have a look at https://github.com/masagrator/ReverseNX-Tool/compare/3.0.1...master for a temporary solution as it seems the fix is taking forever to be implemented in Borealis.

It's doing two things:
1. Some text scaling
2. It has an option to hide the left menu tab: https://raw.githubusercontent.com/masagrator/ReverseNX-Tool/master/docs/Screen1.jpg

**Comment by nadrino** [comment]
Intersting! I will take a look on how to implement that!
