### ISSUE TITLE
Feature suggestions to make SMM more user friendly

### ISSUE THREAD

**Issue by micah686** [nadrino/SimpleModManager#12]
Here's some changes that you might want to add that would make the tool more user friendly:
1) Change the color of inactive mods to a light gray, in order to be able to easily identify which ones are active/inactive at a glance
2)Perhaps add support for extended information about a mod. Maybe there could be a metadata.txt that could be placed in /mods/<NameOfTheGame>/<NameOfTheMod>. Then, you could have make it so when the user presses Y, it would bring up the information contained within the metadata file. THis could be useful for large mods, or for mods that need to be applied in a particular order.

**Comment by nadrino** [comment]
Hi @micah686,

1. Like that ?
![2020071317514900-09C5B0436A5018B3E6486254154AEC43](https://user-images.githubusercontent.com/17473586/87325509-d2449200-c531-11ea-90df-0259462e54a4.jpg)

2. Good point, I'm actually planning to implement an extra popup menu on each mod to provide more informations. For the metadata file feature, it's also a great idea. We need to identify what type of content we want to be displayed.

**Comment by micah686** [comment]
Taking a lot of this from the BOTW mod Loader, but maybe something like the following:
Name, URL of Mod, Image(s) for mod (could either be a url of an image, or a local image), Version number, and description

**Comment by micah686** [comment]
Two more features that I think would be helpful.
1) Add an entry in the "options" to delete all files in a particular contents folder. So if there are any leftover files in the contents/{TITLE_ID}/ folder, it could clean them out, so you know you don't have any remainders of a mod
2)Add an option to skip the checks when installing the mods. Some mod packs have a huge amount of files, and doing a check takes up a considerable amount of time. Maybe if you held R while pressing OK to install the mods, it would skip the checking of the files.

**Comment by nadrino** [comment]
Sorry for the late response! I don't have much time these days to work on SMM. I should be able to implent what you suggested by mid of October I would say.

**Comment by micah686** [comment]
That's fine. These are just "nice to haves" vs needed
