### ISSUE TITLE
game name issue

### ISSUE THREAD

**Issue by kamikazilucas** [nadrino/SimpleModManager#15]
can someone tell me the accurate names for the games i put pokemon sword as the folder name but it says no game folders have been found

**Comment by nadrino** [comment]
You need to put mods in it.
SMM recognize the game for each mod folder by searching for a subfolder which is a titleID. If you only put the name of the game on the mod folder but no mod in it, there is no way it can recognize and display the icon. 

P.-S. And by "mods", I mean mods that affect the "/atmosphere/content/" folder. As opposed to patches (like 60fps patch), which are only files placed in "exefs_patches" folder. Those don't need a subfolder named with the corresponding titleID.

**Comment by kamikazilucas** [comment]
i did the folder has a contents folder with contents inside it , should i put the contents folder in another folder with the game title id then?

**Comment by nadrino** [comment]
Well, normally your mod folder should look like this (example):
/mods/Pokemon/MyGreatMod/contents/<TitleID>/...

Is it how it looks?

**Comment by kamikazilucas** [comment]
ok i looked and the title id is there so i dont understand why it wont work

**Comment by nadrino** [comment]
Do you have the game installed on your Switch ? If not, the titleID image is not present in the NAND.
Also, did you check with SMM in the Options if the titleID has been found?

**Comment by kamikazilucas** [comment]
how do i check that?

**Comment by nadrino** [comment]
Open SMM, select your mod folder, go to the "Options" tab on the left, and the very last item will be the detected titleID

**Comment by kamikazilucas** [comment]
yeah nothing shows up just the option to go to the old gui

**Comment by nadrino** [comment]
If you see the option "Switch to the old gui", then you didnt select your game folder!

**Comment by kamikazilucas** [comment]
wdym select the game folder?

**Comment by nadrino** [comment]
Does the folder "Pokemon..." you created appears when you open SMM ?

**Comment by kamikazilucas** [comment]
no it dosent

**Comment by kamikazilucas** [comment]
![Uploading [20201001_145710.jpg…]()]([url](url))

**Comment by kamikazilucas** [comment]
[https://imgur.com/a/inf2F95](url)

**Comment by nadrino** [comment]
Oh I think see the problem here!
The "mods" folder has to be located in the root of the SD card! -> "/mods/", not "/atmosphere/Mods" like you show on the screenshot

**Comment by kamikazilucas** [comment]
yeah ok it works now thanks
