### ISSUE TITLE
No longer working with latest atmosphere

### ISSUE THREAD

**Issue by jockeyxmc** [nadrino/SimpleModManager#18]
as title says, its no longer working with the latest version of atmosphere

**Comment by fennectech** [comment]
Its dropping shit in /atmosphere instead of /atmosphere/contents eeee

**Comment by fennectech** [comment]
i was able to resolve this by editing the config file tho.

**Comment by XargonWan** [comment]
> i was able to resolve this by editing the config file tho.

Can you please explain how?

**Comment by fennectech** [comment]
This was the result of a change to mods that allows them to be able to drop files outside of the contents folder.     Youll have to rearrange your mods to add the contents folder in the folders
