### ISSUE TITLE
SimpleModManager development

### ISSUE THREAD

**Issue by lowburger** [nadrino/SimpleModManager#21]
Hi, thx for this great program! I just ask if you will continue the develpment or now it's end? Some feature on the issue like moving the large mod will be great. Thx

**Comment by Witherking25** [comment]
If this is dead, can I pick it back up on my fork?

**Comment by Witherking25** [comment]
Apparently it’s not dead he was just very busy

**Comment by lowburger** [comment]
> 
> 
> Apparently it’s not dead he was just very busy

I see thx. I wonder if anyone could look at that issue 7, it can really help this great homebrew. https://github.com/nadrino/SimpleModManager/issues/7

**Comment by nadrino** [comment]
Ok the master branch is now fixed and updated to the latest libnx guys 😛
