### ISSUE TITLE
Comipiling nro file issues

### ISSUE THREAD

**Issue by anthsalmo** [nadrino/SimpleModManager#22]
Hi. First Thanks for you amazing app
I trying to compile my own nro file just for a litle change in the addres to install the mods, for example I want to modified the install-mods-base-folder from "/atmosphere/" to "atmosphere/contents/" and "/sxos/" to "/sxos/titles/" because I use both CFW in my switch to test, and I dont want to duplicate the files in the MODS folder just for this name change. However, Always I get the following error:
 "--Configuring incomplete, errors occurred!" I expent a lot of time looking for how to fix this withiot luck.
Could you help?

My specs 
OS Windows 10, python 3.10, cmake 3.22.0, devkitpro, Cygwin 3.3.1, Visual Studio 2022.

Error Details:

PS C:\SimpleModManager-2.0.4\build> cmake ../ -DCMAKE_TOOLCHAIN_FILE=../devkita64-libnx.cmake
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.30.30705.0
-- The CXX compiler identification is MSVC 19.30.30705.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at cmake/utils.cmake:14 (message):
  This helper can only be used if you are using the Switch toolchain file.
Call Stack (most recent call first):
  cmake/FindLIBNX.cmake:10 (cmake_panic)
  CMakeLists.txt:15 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/devkitPro/examples/switch/a_Probando/build/CMakeFiles/CMakeOutput.log".
PS C:\devkitPro\examples\switch\a_Probando\build>

**Comment by nadrino** [comment]
Hey @anthsalmo, it's been a while since I didn't rebuild SimpleModManager. And quite some things have changed in libnx.
I've fixed the issues in the latest commit of master. So don't hesitate to `git pull` 🙂 

The error you have:
```
Call Stack (most recent call first):
cmake/FindLIBNX.cmake:10 (cmake_panic)
CMakeLists.txt:15 (find_package)
```
is probably because you didn't provide the toolchain to CMake:
```
cmake -D CMAKE_TOOLCHAIN_FILE=../devkita64-libnx.cmake ../
```

**However**!! What you are trying to do is already possible with the latest build 😄 
The parameter you seek (`install-mods-base-folder`) can be changed in the file: `/config/SimpleModManager/parameters.ini`. Inside you will find this:

```
########################################
# preset that can be changed in the app
preset = default

# base folder where mods are installed
install-mods-base-folder = /atmosphere/
########################################
```

Just change the path to the one you whish 😛

**Comment by anthsalmo** [comment]
Thank you for Reply. I couldn't compile the file, but you helped me a lot by telling me where to apply the change!
