### ISSUE TITLE
Mod downloader support?

### ISSUE THREAD

**Issue by snoozbuster** [nadrino/SimpleModManager#25]
I was looking at the [gamebanana API](https://api.gamebanana.com/), which as far as I know is the premiere source for switch game mods. I'd love to fork this project and see if I can add support to it to be able to browse mods on gamebanana and directly download them to be applied (using the pre-existing functionality), sorta like how the HB app store works but for game mods. Caveat: I haven't done any C programming in a long time and haven't done any switch programming before at all, so who knows if I will even be successful in any of this.

I'm definitely not asking for someone to do this for me, but it would help me a ton if I could get some primer resources on things like:

* how to read installed switch titles
* how to initialize the network stack and make requests out
* the basic architecture of the app and what parts I would be especially interested in for a project like this

Feel free to redirect me to a wiki or other switch library docs for the first two, happy to read those myself I just don't know where to start (and either way, knowing the basic app architecture would be incredibly useful). 

If I was successful in adding this in a fork - would you be interested in integrating it back into upstream? I'd be happy to open a PR.

**Comment by Witherking25** [comment]
the problem with this is that there isn't any well defined format for the mod archives. the current method rely on a human deciding what goes where

**Comment by Witherking25** [comment]
you could have a prompt for the user to choose the root directory of the mod, but there aren't many other options

**Comment by Witherking25** [comment]
for the web requests, there is the curl portlib.

and as for the structure, look at the changes i made in my fork when i added the plugin browser page

**Comment by Witherking25** [comment]
if you need help setting things up just ask :)

**Comment by Witherking25** [comment]
I recommend working off of my fork until it gets merged because i fixed some compile issues from my last merge.

**Comment by snoozbuster** [comment]
interesting, I will have to download some mods off gamebanana for testing. I thought the format was pretty standard, or at least of the mods I've downloaded I thought the process was the same for each of them. I guess its kinda up to the mod packager though huh

**Comment by Witherking25** [comment]
https://switchbrew.github.io/libnx/ns_8h.html#a801a457720759c13f79ab31df1e82c51

For listing titles

**Comment by snoozbuster** [comment]
Appreciate it! I’ll definitely take a look at all this. I’ve been caught up in work and the new Destiny 2 DLC - but I’ll definitely be back to spend some time on this soon!

**Comment by Witherking25** [comment]
https://github.com/withertech/NXModToolkit

**Comment by Witherking25** [comment]
Example mod
[example.zip](https://github.com/nadrino/SimpleModManager/files/8147841/example.zip)

Python wheel for the completed toolkit
[NXModToolkit-1.0.dev0-py3-none-any.zip](https://github.com/nadrino/SimpleModManager/files/8147842/NXModToolkit-1.0.dev0-py3-none-any.zip)

JSON Schema for mod.json
https://withertech.com/SimpleModManagerMod.json

**Comment by Witherking25** [comment]
(Wait till my fork gets re merged to fix those dumb compile errors)
