### ISSUE TITLE
[BUG] Switch between docked mode and portable mode during a mod installation make the console hang

### ISSUE THREAD

**Issue by Fuzzy2319** [nadrino/SimpleModManager#30]
I'm using atmosphere 1.4.0 hekate 5.9.0 and 15.0.0 firmware on my switch.

When I installed a mod I accidentally undocked my switch during the installation resulting on a black screen and a corrupted installation on the SD card. After a cleanup it worked again.

**Comment by nadrino** [comment]
Should be fixed on master
