### ISSUE TITLE
Perhaps the README should be updated.

### ISSUE THREAD

**Issue by Jonblu11** [nadrino/SimpleModManager#5]
As of Atmosphere's 0.10.0 update, Atmosphere no longer uses the /title/ folder and instead uses /contents/. The instructions, specifically the example portion, still reflect the previous Atmosphere versions and can cause confusion.

Edit: As someone who *just* got into modding, I spent the last 20 minutes trying to figure out why my mods weren't working. Hopefully this will spare someone else from the search I went through.

**Comment by nadrino** [comment]
True, I will update the readme. In fact I updated the gbatemp forum page but not the github README... Thanks for the issue :)
