### ISSUE TITLE
Mod Manager isn't actually putting the mods in contents folder or titles  folder

### ISSUE THREAD

**Issue by MadMax1960** [nadrino/SimpleModManager#6]
Same as title. It isn't actually pushing any of the files into the contents or titles folder. I did it multiple times, multiple mods, on multiple different games. Everytime it acted like it was installing the mods, but it didn't actually do anything.

**Comment by nadrino** [comment]
Can you show me your config file ? And a schem of your files inside your mods folder ?

**Comment by Stuntaneous** [comment]
Check your folder structure of the files in /mods/

**Comment by MadMax1960** [comment]
Ah sorry for not responding before.

I fixed the problem by simply changing where it puts the mods in the
config, had to rearrange all of my mod folders, but that's not a big deal.

**Comment by nadrino** [comment]
Ok cool, thanks for your answer! I close the issue.
