### ISSUE TITLE
Suggestion - change file identification method

### ISSUE THREAD

**Issue by pixeltester** [nadrino/SimpleModManager#8]
I use  this app all the time, it's excellent but there are two problems that stand out to me:

First problem: the method of file handling especially for huge mods - I already made a suggestion regarding that in issue #7 

Second problem: file identification. Using size creates a lot of conflicts for certain games and in the some instances you can end up with a list of many "Active" and "Partial" with only one mod activated.

So my suggestion for the second problem would be to switch to CRC32 hashing instead. It shouldn't be too slow, it's far more accurate and will eliminate all of those problems.

Regardless of using size or hash check I also wonder if you should add a "Scan" option in the app instead of scanning by default every time we open the mod list for a game? If I quickly exit and then return to the mod list because I forgot one mod, I don't want to scan everything again. I know this means you need to save the status of files somewhere though.

**Comment by nadrino** [comment]
Done :).
Thanks for the suggestion.
