### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Witherking25** [nadrino/SimpleModManager#9]
When I try to launch simple mod manager, the application crashes

**Comment by nadrino** [comment]
Which Atmosphere version are you using ?

**Comment by Witherking25** [comment]
Latest

**Comment by Witherking25** [comment]
I’ve tried reinstalling at least 5 different ways 2 times each

**Comment by Witherking25** [comment]
Even compiling from source

**Comment by nadrino** [comment]
Alright, I'm gonna update and try this out.

**Comment by nadrino** [comment]
Still have this problem with the latest v1.5.0 ?

**Comment by Witherking25** [comment]
i got a new sdcard a couple of days ago and im currently transferring my stuff over

**Comment by nadrino** [comment]
Alright, let me know

**Comment by Witherking25** [comment]
i hate it when my sdcard gets corrupted

**Comment by Witherking25** [comment]
ill get it sorted out

**Comment by nadrino** [comment]
Is it formated in exFat ? If it is, you should know that the Switch driver is not very stable with exFat. Better use the good old FAT32 format.

**Comment by Witherking25** [comment]
Fat32
I have a shit 256 gb sdcard from china

**Comment by Witherking25** [comment]
I’m aware of the wonkyness of the exfat driver

**Comment by nadrino** [comment]
Oh I see, did you check it's really a 256Gb ? It happens there is some scams sdcards.

**Comment by Witherking25** [comment]
Oh it is

**Comment by Witherking25** [comment]
It’s just not very reliable

**Comment by pixeltester** [comment]
SimpleModManager has worked perfectly with every version of atmosphere since it was released including the latest version: SimpleModManager 1.5.0 on Atmosphere 0.12.0

This seems like hardware or user error rather than an issue for this homebrew.

**Comment by nadrino** [comment]
You're right. I'm closing the thread.
